<a href="https://colab.research.google.com/github/Nirtika123/product-dataset-eda/blob/main/da_lab1(8_7).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df = pd.read_csv('lab1dataset.csv')

1. How many product records are available in the dataset?

In [ ]:
pd.read_csv("lab1dataset.csv")

     Category   Price    Rating         Stock  Discount
0         NaN  5548.0  1.870322           NaN       0.0
1         NaN  3045.0  4.757798           NaN      38.0
2         NaN  4004.0       NaN      In Stock       0.0
3         NaN  4808.0  1.492085           NaN      33.0
4         NaN  1817.0       NaN  Out of Stock      23.0
...       ...     ...       ...           ...       ...
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0
4361      NaN     NaN  2.184471           NaN       0.0

[4362 rows x 5 columns]

2. How many columns are available in the dataset?

In [ ]:
df.shape[1]

5

3. What product-related details are captured in the dataset?

In [ ]:
df.columns.tolist()

['Category', 'Price', 'Rating', 'Stock', 'Discount']

4.What are the first five product records in the dataset?

In [ ]:
df.head()

  Category   Price    Rating         Stock  Discount
0      NaN  5548.0  1.870322           NaN       0.0
1      NaN  3045.0  4.757798           NaN      38.0
2      NaN  4004.0       NaN      In Stock       0.0
3      NaN  4808.0  1.492085           NaN      33.0
4      NaN  1817.0       NaN  Out of Stock      23.0

5. What are the last five product records in the dataset?

In [ ]:
df.tail()

     Category   Price    Rating         Stock  Discount
4357      NaN  4436.0  4.728335           NaN      49.0
4358        B  6236.0       NaN  Out of Stock       4.0
4359      NaN  3283.0       NaN  Out of Stock       9.0
4360        D  2999.0  4.425995           NaN      40.0
4361      NaN     NaN  2.184471           NaN       0.0

6. What type of data is stored in each column?

In [ ]:
df.dtypes

Category     object
Price       float64
Rating      float64
Stock        object
Discount    float64
dtype: object

7. Which columns can be used for numerical analysis?

In [ ]:
df.select_dtypes(include="number").columns.tolist()

['Price', 'Rating', 'Discount']

8. Which columns can be used for category-wise analysis?

In [ ]:
df.select_dtypes(include="object").columns.tolist()

['Category', 'Stock']

9. How many total data values are present in the dataset?

In [ ]:
df.size

21810

10. What is the non-null count for each column?

In [ ]:
df.notnull().sum()

Category    1614
Price       4188
Rating      2312
Stock       3010
Discount    3970
dtype: int64

11. How many missing values are present in each column?

In [ ]:
df.isnull().sum()

Category    2748
Price        174
Rating      2050
Stock       1352
Discount     392
dtype: int64

12. What is the total number of missing values in the dataset?

In [ ]:
df.isnull().sum().sum()

np.int64(6716)

13. Which column has the highest number of missing values?

In [ ]:
df.isnull().sum().idxmax()

'Category'

14. Which column has the lowest number of missing values?

In [ ]:
df.isnull().sum().idxmin()

'Price'

15. What percentage of values are missing in each column?

In [ ]:
(df.isnull().sum() / len(df)) * 100

Category    62.998624
Price        3.988996
Rating      46.996790
Stock       30.994956
Discount     8.986703
dtype: float64

16. Which columns need attention because of missing values?

In [ ]:
df.columns[df.isnull().sum() > 0]

Index(['Category', 'Price', 'Rating', 'Stock', 'Discount'], dtype='object')

17. How many duplicate product records are present in the dataset?

In [ ]:
df.duplicated().sum()

np.int64(15)

18. What are the duplicate records found in the dataset?

In [ ]:
df[df.duplicated()]

     Category  Price  Rating         Stock  Discount
505       NaN    NaN     NaN           NaN       NaN
1746      NaN    NaN     NaN      In Stock      44.0
1760      NaN    NaN     NaN      In Stock      44.0
2051      NaN    NaN     NaN           NaN       NaN
2124      NaN    NaN     NaN  Out of Stock       NaN
2241      NaN    NaN     NaN  Out of Stock       NaN
3302      NaN    NaN     NaN      In Stock       1.0
3314      NaN    NaN     NaN  Out of Stock      16.0
3527      NaN    NaN     NaN  Out of Stock      26.0
3553      NaN    NaN     NaN  Out of Stock      28.0
3918      NaN    NaN     NaN           NaN      42.0
3957      NaN    NaN     NaN  Out of Stock       NaN
4001      NaN    NaN     NaN      In Stock       1.0
4344      NaN    NaN     NaN           NaN       0.0
4355      NaN    NaN     NaN      In Stock      46.0

19. Is the dataset free from duplicate records?

In [ ]:
df.duplicated().sum() == 0

NameError: name 'df' is not defined

20. What is the lowest product price in the dataset?

In [ ]:
df["Price"].min()

102.0

21. What is the highest product price in the dataset?

In [ ]:
df["Price"].max()

9999.0

22. What is the average product price?

In [ ]:
df["Price"].mean()

np.float64(5016.970630372492)

23. What is the complete statistical summary of product price?

In [ ]:
df["Price"].describe()

count    4188.000000
mean     5016.970630
std      2839.984813
min       102.000000
25%      2628.250000
50%      4996.500000
75%      7418.000000
max      9999.000000
Name: Price, dtype: float64

24. What is the lowest customer rating in the dataset?

In [ ]:
df["Rating"].min()

1.0003662024741131

25. What is the highest customer rating in the dataset?

In [ ]:
df["Rating"].max()

4.997817693458396

26. What is the average customer rating?

In [ ]:
df["Rating"].mean()

np.float64(3.0382925191086185)

27. What is the highest discount offered on a product?

In [ ]:
df["Discount"].max()

49.0

28. What is the average discount offered on products?

In [ ]:
df["Discount"].mean()

np.float64(24.516624685138538)

29. How many unique product categories are available in the dataset?

In [ ]:
df["Category"].nunique()

4

30. Which stock status occurs most frequently in the dataset?

In [ ]:
df["Stock"].value_counts().idxmax()

'In Stock'